export const SLOTS_REQUESTED = "SLOTS_REQUESTED";
export const SLOTS_RECEIVED = "SLOTS_RECEIVED";
export const SLOTS_FAILED = "SLOTS_FAILED";

export const PFO_REQUESTED = "PFO_REQUESTED";
export const PFO_RECEIVED = "PFO_RECEIVED";
export const PFO_FAILED = "PFO_FAILED";

export const AUTH_REQUESTED = "AUTH_REQUESTED";
export const AUTH_RECEIVED = "AUTH_RECEIVED";
export const AUTH_FAILED = "AUTH_FAILED";

